"""initial schema (§9 core tables)

Revision ID: 0001
Revises:
Create Date: 2026-06-09

First migration: create the whole §9 schema from the model metadata (single source of
truth, cross-dialect — Postgres + SQLite). Subsequent changes get explicit, autogenerated
migrations; Timescale hypertables (odds_snapshots/prices) arrive in their own migration at M2.1.
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op

from sportsdata_agents.data.base import Base

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    Base.metadata.create_all(op.get_bind())


def downgrade() -> None:
    Base.metadata.drop_all(op.get_bind())
