#!/bin/sh
# Publish site/ to the PUBLIC Pages repo (sportsdata-site). The product repos
# stay private; only these marketing assets go public. Run after editing site/.
set -e
REPO_DIR="$(cd "$(dirname "$0")/.." && pwd)"
WORK="$(mktemp -d)"
git clone --depth 1 "https://github.com/DanielTomaro13/sportsdata-site.git" "$WORK"
cp "$REPO_DIR"/site/index.html "$REPO_DIR"/site/demo-fallback.json "$WORK"/
# stripe.json (Payment Link URLs) is generated by setup-stripe.py and is not committed
# to the product repo; ship it to the public site only when it exists.
[ -f "$REPO_DIR"/site/stripe.json ] && cp "$REPO_DIR"/site/stripe.json "$WORK"/
cd "$WORK"
git add -A
git diff --cached --quiet && { echo "site unchanged"; exit 0; }
# noreply author: never leak a personal email into the public repo's history
git -c user.name="DanielTomaro13" -c user.email="DanielTomaro13@users.noreply.github.com" \
    commit -m "publish site update"
git push origin main
echo "published — live at https://danieltomaro13.github.io/sportsdata-site/ in ~a minute"
